apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }} 
roleRef:
  kind: ClusterRole
  name: keit-pod-reader
  apiGroup: rbac.authorization.k8s.io

