{
 "title": "Carbon intensity EKS - KEIT (Ierland)",
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kepler_container_package_joules_total, container_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}, pod_name)"
    }
   },
   { "name": "watt_per_second_to_kWh", "query": "0.000000277777777777778" },
   { "name": "PUE_avr_aws", "query": "1.135" },
   { "name": "seconds_five_years", "query": "157766400" },
   {
    "name": "Energy",
    "label": "E",
    "query": {
     "query": "query_result(scalar(sum(increase(kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[ $__range ])) * $watt_per_second_to_kWh))"
    }
   },
   {
    "name": "EnergyCarbonIntensity",
    "label": "I",
    "query": {
     "query": "query_result(scalar(avg(avg_over_time(grid_intensity_carbon_average{is_estimated=\"true\"}[$__range]))))"
    }
   },
   {
    "name": "Embodied",
    "label": "M",
    "query": {
     "query": "query_result(scalar(($__range_s/$seconds_five_years)*sum(eks_node_embedded_value{node_name=~\".*\"})*1000))"
    }
   },
   {
    "name": "SCI",
    "query": {
     "query": "query_result((($Energy * $EnergyCarbonIntensity * $PUE_avr_aws) + $Embodied))"
    }
   }
  ]
 },
 "panels": [
  { "title": "PUE aws - eu-west-1", "type": "text", "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 }, "options": { "content": "${PUE_avr_aws}" } },
  { "title": "SCI index components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Energy (E)",
   "type": "text",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 3 },
   "options": {
    "content": "# [Energy (E)](https://sci-guide.greensoftware.foundation/E/)\n\n### What are the different ways to  calculate energy?​\n\nSoftware systems cause emissions through the hardware that they operate on, both through the energy that the physical hardware consumes and the emissions associated with manufacturing the hardware.\n\nMore info [here](https://sci-guide.greensoftware.foundation/E/)."
   }
  },
  {
   "title": "Energy Carbon Intensity (I)",
   "type": "text",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 3 },
   "options": {
    "content": "# [Energy Carbon Intensity (I)](https://sci-guide.greensoftware.foundation/I)\n\nThe carbon intensity of electricity is a measure of how much carbon (CO2eq) emissions are produced per kilowatt-hour (kWh) of electricity consumed.\n\nThe only value that matters if you’re trying to optimise the scheduling of your computing in real-time is the marginal emissions intensity. This is the emissions intensity of the marginal power plant which will be turned up if you schedule some computing at that moment.\n\nMore info [here](https://sci-guide.greensoftware.foundation/I/)."
   }
  },
  {
   "title": "Embodied (M)",
   "type": "text",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 3 },
   "options": {
    "content": "# [Embodied (M)](https://sci-guide.greensoftware.foundation/M/)\n\nEmbodied carbon (also known as embedded carbon) is the amount of carbon emitted during the creation and disposal of a hardware device.\n\nWhen software runs on a device, a fraction of the total embodied emissions of the device is allocated to the software. This is the value of M that you need to calculate in the SCI equation.\n\nMore info [here](https://sci-guide.greensoftware.foundation/M/)."
   }
  },
  {
   "title": "Functional Unit (R)",
   "type": "text",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 3 },
   "options": {
    "content": "# [Functional Unit (R)](https://sci-guide.greensoftware.foundation/R/)\n\nThe functional unit defines how your application scales. For instance, if your application scales by APIs then choose API as your functional unit.\n\nFor instance, if you are running on the cloud, you can get the total API request/second from the cloud metrics of your API gateway. You can get the data from a production instance or carry out lab-based testing (i.e stress testing) to get how much CO2e is emitted per unit of the functional unit.\n\nMore info [here](https://sci-guide.greensoftware.foundation/R/)."
   }
  },
  {
   "title": "Software Carbon Intensity equation",
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 3 },
   "options": {
    "content": "\n\n\n# [SCI Equation = ](https://sci-guide.greensoftware.foundation/)\n# [(E * I) + M per R](https://sci-guide.greensoftware.foundation/)"
   }
  },
  {
   "title": "Software Carbon Intensity (SCI) index of KEIT EKS cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Energy (E) in kWh - Total.",
   "type": "stat",
   "description": "Energy in kWh",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[ $__range ])) * $watt_per_second_to_kWh\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Emissions (I) in gCO2e/kWh - Ierland (estimated)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(grid_intensity_carbon_average{is_estimated=\"true\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Embodied (M) in gCO2e - EKS",
   "type": "gauge",
   "description": "Embodied Carbon Emissions",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "($__range_s/157766400)*sum(eks_node_embedded_value{node_name=~\".*\"})*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Functional Unit (U) - EKS", "type": "text", "gridPos": { "h": 9, "w": 5, "x": 15, "y": 14 }, "options": { "content": "The whole EKS cluster" } },
  {
   "title": "Carbon Intensity (gCO2eq)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(($Energy * $EnergyCarbonIntensity * $PUE_avr_aws) + ($__range_s/157766400)*sum(eks_node_embedded_value{node_name=~\".*\"})*1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Power Consumption (PKG+DRAM+OTHER+GPU) by Namespace (kWh)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_namespace) (\n  increase(\n      (kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__range])\n  )\n) * $watt_per_second_to_kWh ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Embodied (M) percentage of SCI",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "(($__range_s/157766400)*sum(eks_node_embedded_value{node_name=~\".*\"})*1000 / (($Energy * $EnergyCarbonIntensity * $PUE_avr_aws) + ($__range_s/157766400)*sum(eks_node_embedded_value{node_name=~\".*\"})*1000)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All CPU usage percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "avg(100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[15m:1m])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All servers CPU usage percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[15m:1m])) * 100)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carbon Intesity gCO2e per kWh (estimated)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "grid_intensity_carbon_average{is_estimated=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Power Consumption (PKG+DRAM+OTHER+GPU) by Namespace (kWh)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_namespace) (\n  increase(\n      (kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__range])\n  )\n) * $watt_per_second_to_kWh ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energy (E) in kWh - KEIT cluster",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 7, "y": 71 },
   "targets": [
    {
     "expr": "sum(increase(\n          (kepler_container_joules_total{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__range])\n      )\n   ) * $watt_per_second_to_kWh",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "How many flight KM",
   "type": "stat",
   "description": "see:\nhttps://github.com/hoernschen/grasp/tree/main/src/lib/comparison/distance\n\nPlane: 122.72 g per km",
   "gridPos": { "h": 14, "w": 5, "x": 16, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((($Energy * $EnergyCarbonIntensity * $PUE_avr_aws) + ($__range_s/157766400)*sum(eks_node_embedded_value{node_name=~\".*\"})*1000))/122.72",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}