{{- if and .Values.secret.create (not .Values.secret.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: scaleway-footprint-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SCW_ORG_ID: {{ required "secret.scwOrgId is required when secret.create=true" .Values.secret.scwOrgId | quote }}
  SCW_SECRET_KEY: {{ required "secret.scwSecretKey is required when secret.create=true" .Values.secret.scwSecretKey | quote }}
{{- end }}
