replicaCount: 1

image:
  repository: ghcr.io/aknostic/keit
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

namespace: keit

boavizta:
  image:
    repository: ghcr.io/boavizta/boaviztapi
    tag: latest
    pullPolicy: Always
  replicaCount: 1

servicemonitor:
  enabled: true
  interval: 1m
  scrapeTimeout: 1m
