name: Build and Dockerize KIET Go Application

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests targeting the main branch

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Step 3: Install dependencies
      - name: Install Go dependencies and build
        run: |
          cd eks
          go mod init keit
          go mod tidy
          go build -o keit . 
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o keit .
          docker build -t keit .

      # Step 4: Read and increment version
      - name: Increment version
        id: version
        run: |
          # Read the current version from the VERSION file
          VERSION_FILE=eks/VERSION
          if [ ! -f "$VERSION_FILE" ]; then
            echo "0.0.0" > $VERSION_FILE
          fi
          CURRENT_VERSION=$(cat $VERSION_FILE)

          # Increment the patch version
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          # Write the new version to the file
          echo "$NEW_VERSION" > $VERSION_FILE
          echo "version=$NEW_VERSION" >> $GITHUB_ENV

      # Step 5: Build Docker image with new version tag
      - name: Build Docker image
        run: |
          docker build -t keit:${{ env.version }} .

  approve-deployment:
    needs: build-and-dockerize
    runs-on: ubuntu-latest

    steps:
      - name: Await manual approval
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: manual-approval

      # Step 1: Push Docker image to GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag keit:${{ env.version }} ghcr.io/${{ github.repository }}/keit:${{ env.version }}
          docker push ghcr.io/${{ github.repository }}/keit:${{ env.version }}




